from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 400)
        MainWindow.setMinimumSize(QtCore.QSize(650, 400))
        MainWindow.setMaximumSize(QtCore.QSize(650, 400))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/spock.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0, fy:.003, stop:0 rgba(55, 69, 111, 147), stop:0.497326 rgba(19, 55, 99, 200), stop:1 rgba(99, 169, 33, 4));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 8, 624, 33))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 243, 217);\n"
                                "border-color: rgb(0, 0, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.game_text2 = QtWidgets.QLabel(self.centralwidget)
        self.game_text2.setGeometry(QtCore.QRect(90, 307, 454, 56))
        self.game_text2.setStyleSheet("border-color: rgb(226, 255, 254);\n"
                                "color: rgb(255, 255, 255);")
        self.game_text2.setAlignment(QtCore.Qt.AlignCenter)
        self.game_text2.setObjectName("game_text2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 50, 627, 177))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        # image 1
        self.p1_image = QtWidgets.QLabel(self.widget)
        self.p1_image.setScaledContents(True)
        self.p1_image.setMinimumSize(QtCore.QSize(200, 150))
        self.p1_image.setMaximumSize(QtCore.QSize(200, 150))
        self.p1_image.setObjectName("p1_image")
        self.gridLayout.addWidget(self.p1_image, 0, 0, 1, 1)
        self.game_text1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(8)
        self.game_text1.setFont(font)
        self.game_text1.setStyleSheet("color: rgb(255, 255, 255);")
        self.game_text1.setAlignment(QtCore.Qt.AlignCenter)
        self.game_text1.setWordWrap(True)
        self.game_text1.setObjectName("game_text1")
        self.gridLayout.addWidget(self.game_text1, 0, 1, 1, 1)
        # image 2
        self.p2_image = QtWidgets.QLabel(self.widget)
        self.p2_image.setScaledContents(True)
        self.p2_image.setMinimumSize(QtCore.QSize(200, 150))
        self.p2_image.setMaximumSize(QtCore.QSize(200, 150))
        self.p2_image.setObjectName("p2_image")
        self.gridLayout.addWidget(self.p2_image, 0, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(28, 261, 579, 33))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # gesture buttons
        self.rock_button = QtWidgets.QPushButton(self.widget1)
        self.rock_button.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rock_button.setFont(font)
        self.rock_button.setAutoFillBackground(False)
        self.rock_button.setStyleSheet("background-color: lightgray;")
        self.rock_button.setObjectName("rock_button")
        self.rock_button.setEnabled(True)
        self.horizontalLayout.addWidget(self.rock_button)
        self.paper_button = QtWidgets.QPushButton(self.widget1)
        self.paper_button.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.paper_button.setFont(font)
        self.paper_button.setAutoFillBackground(False)
        self.paper_button.setStyleSheet("background-color: lightgray;")
        self.paper_button.setObjectName("paper_button")
        self.horizontalLayout.addWidget(self.paper_button)
        self.scissors_button = QtWidgets.QPushButton(self.widget1)
        self.scissors_button.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.scissors_button.setFont(font)
        self.scissors_button.setAutoFillBackground(False)
        self.scissors_button.setStyleSheet("background-color: lightgray;")
        self.scissors_button.setObjectName("scissors_button")
        self.horizontalLayout.addWidget(self.scissors_button)
        self.lizard_button = QtWidgets.QPushButton(self.widget1)
        self.lizard_button.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lizard_button.setFont(font)
        self.lizard_button.setAutoFillBackground(False)
        self.lizard_button.setStyleSheet("background-color:lightgrey\n;"
                                "selection-color: rgb(158, 208, 255);")
        self.lizard_button.setObjectName("lizard_button")
        self.horizontalLayout.addWidget(self.lizard_button)
        self.spock_button = QtWidgets.QPushButton(self.widget1)
        self.spock_button.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spock_button.setFont(font)
        self.spock_button.setAutoFillBackground(False)
        self.spock_button.setStyleSheet("background-color: lightgray;")
        self.spock_button.setObjectName("spock_button")
        self.horizontalLayout.addWidget(self.spock_button)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(198, 364, 237, 24))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.radio_button1 = QtWidgets.QRadioButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_button1.sizePolicy().hasHeightForWidth())
        self.radio_button1.setSizePolicy(sizePolicy)
        self.radio_button1.setStyleSheet("color: rgb(255, 255, 255);")
        self.radio_button1.setObjectName("radio_button1")
        self.radio_button2 = QtWidgets.QRadioButton(self.splitter)
        self.radio_button2.setStyleSheet("color: rgb(255, 255, 255);")
        self.radio_button2.setChecked(True)
        self.radio_button2.setObjectName("radio_button2")
        MainWindow.setCentralWidget(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setWindowTitle("Rock Paper Scissors Lizard Spock Viewer 1.0")
        self.label.setText("Welcome to Rock Paper Scissors Lizard Spock Viewer 1.0")
        self.game_text2.setText("Choose Player below, then choose your Gesture!!!! ")
        self.game_text1.setText("Click buttons to select a gesture!\n\nRock crushes Scissors\nScissors cuts Paper\nPaper covers Rock\nRock crushes Lizard\nLizard poisons Spock\nSpock smashes Scissors\nScissors decapitates Lizard\nLizard eats Paper\nPaper disproves Spock\nSpock vaporizes Rock")
        self.rock_button.setText("Rock")
        self.paper_button.setText("Paper")
        self.scissors_button.setText("Scissors")
        self.lizard_button.setText("Lizard")
        self.spock_button.setText("Spock")
        self.radio_button1.setText("Player 1")
        self.radio_button2.setText("Player 2")


